// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhscOA6fO_LRRQu9LTMwnBNGI4PZyEbT4',
    appId: '1:872388698023:web:c9677ef0b361eefd99a082',
    messagingSenderId: '872388698023',
    projectId: 'automated-food-ordering-64dc4',
    authDomain: 'automated-food-ordering-64dc4.firebaseapp.com',
    storageBucket: 'automated-food-ordering-64dc4.appspot.com',
    measurementId: 'G-8H7H9TLP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qwKoTVepWkwaWkEIWwNKkAB5cGSbrDs',
    appId: '1:872388698023:android:fe86991bd0ab8aba99a082',
    messagingSenderId: '872388698023',
    projectId: 'automated-food-ordering-64dc4',
    storageBucket: 'automated-food-ordering-64dc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkgiXx7x87iXLWjhETw8t5CFYkerYkVwE',
    appId: '1:872388698023:ios:ac27dae4d248fbe499a082',
    messagingSenderId: '872388698023',
    projectId: 'automated-food-ordering-64dc4',
    storageBucket: 'automated-food-ordering-64dc4.appspot.com',
    androidClientId: '872388698023-nqki37nteu831u2p238pq45753sc2k4s.apps.googleusercontent.com',
    iosClientId: '872388698023-1dh3ebf41hm0rd7fk10mpdou7glgjb9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatedFoodOrderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkgiXx7x87iXLWjhETw8t5CFYkerYkVwE',
    appId: '1:872388698023:ios:ac27dae4d248fbe499a082',
    messagingSenderId: '872388698023',
    projectId: 'automated-food-ordering-64dc4',
    storageBucket: 'automated-food-ordering-64dc4.appspot.com',
    androidClientId: '872388698023-nqki37nteu831u2p238pq45753sc2k4s.apps.googleusercontent.com',
    iosClientId: '872388698023-1dh3ebf41hm0rd7fk10mpdou7glgjb9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatedFoodOrderingSystem',
  );
}
